### ISSUE TITLE
add state metric (e.g 'ok', 'error')

### ISSUE THREAD

**Issue by jcrugzz** [nodejitsu/forza#14]
Looking at the `start` plugin's success and failure functions got me thinking that a state value may be appropriate. The `metric` property is currently used to signify this but I think that can be better used for summing how many failed starts there are and things of that nature. @mmalecki thoughts?

**Comment by mmalecki** [comment]
`start` plugin emits a metric `1` if start is successful and `0` if start failed. State metric isn't needed here yet.

**Comment by jcrugzz** [comment]
@mmalecki yea I saw that but this eliminates the ability to be able to count the number of failed starts as its `metric` property is 0. Granted idk if that is useful at the moment so I'll leave it up to your discretion.
