### ISSUE TITLE
Resolve instruments via DNS

### ISSUE THREAD

**Issue by indexzero** [nodejitsu/forza#16]
RIght now we rely on IP addresses only. It would be ideal to do a DNS resolve on those things so we could use things like `http://metrics.nodejitsu.com`

**Comment by indexzero** [comment]
@mmalecki Ping? We are seeing a real necessity for this in production because the distribution from `forza` producers is not uniform across our multiplexers. 

cc/ @jcrugzz

**Comment by indexzero** [comment]
@mmalecki This should be possible using a pure libuv approach: https://github.com/joyent/libuv#feature-highlights

**Comment by jcrugzz** [comment]
Yea this would be awesome! Let me know if I can help @mmalecki :).
