### ISSUE TITLE
dont allow people to listen on port 80

### ISSUE THREAD

**Issue by jcrugzz** [nodejitsu/forza#17]
produces a `warn: error raised: Error: listen EINVAL` error and puts their app in a questionable state. We should autocorrect to 1024 like we did before.

**Comment by edef1c** [comment]
this goes for all ports <1024, no?

**Comment by jcrugzz** [comment]
@nathan7 highly probable

**Comment by mmalecki** [comment]
Fixed in 1f4327d211945f2b8032a6ee3655e4d111af3c42.
