### ISSUE TITLE
app listens on port 1024, says 1025 in couch doc.

### ISSUE THREAD

**Issue by jcrugzz** [nodejitsu/forza#20]
@julianduque and I came to notice that some of the apps that seem to have the correct processes running on the drone, end up in a state where they cannot receive requests from the balancer. (`ECONNREFUSED`). It has been a common case to see this happen with apps trying to listen on port 1024 from the monitoring I've done today.

**Comment by julianduque** [comment]
if I deploy an app with port 1024, it will save to the db 1024.
but if I delploy to port 80, it will listen on 1024 but save 1025

**Comment by edef1c** [comment]
@julianduque awesome work discovering that

**Comment by mmalecki** [comment]
@julianduque awesome, that makes it incredibly easier to debug. Thanks!

**Comment by Swaagie** [comment]
This will affect multiple customers, status and IRC channel reflect the workaround (e.g. port higher than 1024) for the time being. As soon as this is fixed both channels should be updated. Status is still green flagged btw

**Comment by mmalecki** [comment]
This was fixed in 1f4327d211945f2b8032a6ee3655e4d111af3c42.
