### ISSUE TITLE
Uh... yeah. That.

### ISSUE THREAD

**Issue by Southern** [nodejitsu/forza#23]
I haz no clue.

```
solenoid 48960 76642   0 05:09:23 ?           0:00 aeternum run -o /opt/run/forza.log -- forza -h 72.2.115.35:8556 -h 72.2.115.133
solenoid 48961 48960   0 05:09:23 ?           0:00 forza -h 72.2.115.35:8556 -h 72.2.115.133:8556 -h 72.2.115.112:8556 -h 72.2.115
solenoid 39517 76642   0 04:46:31 ?           0:00 forza -h 72.2.115.35:8556 -h 72.2.115.133:8556 -h 72.2.115.112:8556 -h 72.2.115
```

/cc @jcrugzz

**Comment by indexzero** [comment]
@Southern I noticed the same thing. This is my proposed solution: https://github.com/nodejitsu/solenoid/pull/21

**Comment by Swaagie** [comment]
Above proposed and merged fix should perhaps also `pkill -9 node` as I found a zombie running the process below. Process ID `37395` should not be running on this drone. Manually purged with fire

```
solenoid 37395  0.0  0.2 267568 201900 ?        S 13:26:17 10:31 /opt/engines/node/v0.8.25/bin/node worker.js
solenoid 75084  0.0  0.0 2584  820 ?        S 21:37:34  0:00 aeternum run -o /opt/run/forza.log -- forza -h 72.2.115.35:8556 -h 72.2.115.133:8556 -h 72.2.115.112:8556 -h 72.2.115.136:8556 -h 72.2.115.155:8556 --app-user ladestasjoner --app-name chargelizer-realtime -- /opt/engines/node/v0.10.16/bin/node ./bin/server.js
solenoid 75085  0.0  0.0 3088 1052 ?        S 21:37:34  0:07 forza -h 72.2.115.35:8556 -h 72.2.115.133:8556 -h 72.2.115.112:8556 -h 72.2.115.136:8556 -h 72.2.115.155:8556 --app-user ladestasjoner --app-name chargelizer-realtime -- /opt/engines/node/v0.10.16/bin/node ./bin/server.js
solenoid 75086  0.0  0.1 80440 37444 ?        S 21:37:34  0:24 /opt/engines/node/v0.10.16/bin/node ./bin/server.js
```

**Comment by jcrugzz** [comment]
@Swaagie good looks, I actually ran into the same thing when `baton ssh`ing into a random drone. Disconcerting to say the least! Forza must lose control of the node process somehow in the case where it is killed or something of the sort. It is now handled in [solenoid](https://github.com/nodejitsu/solenoid/blob/master/lib/solenoid.js#L106-L123)

**Comment by jcrugzz** [comment]
This is fixed in solenoid. We run a `pkill forza` instead of a `pkill -9 forza` in order for forza to recognize the `SIGTERM` and cleanly kill the child node process.
