### ISSUE TITLE
App running on port 6200 but saves in db a random port 

### ISSUE THREAD

**Issue by julianduque** [nodejitsu/forza#26]
`blankstatement/blankstatement-site` should be running on port 6200 but sometimes in the database is saved a random port and in the drone the app keeps running on 6200

**Comment by julianduque** [comment]
Confirmed.

It's bunyan-syslog package starting an UDP server on a random port, forza is getting that port as app port.

**Comment by mmalecki** [comment]
Great job finding that out @julianduque! Thanks dude. Looking at it now.

**Comment by mmalecki** [comment]
Okay, so it seems like we have to call `getsockopt` with `SO_TYPE` to check if socket is a `SOCK_DGRAM` socket.
