### ISSUE TITLE
Heartbeat plugin

### ISSUE THREAD

**Issue by jcrugzz** [nodejitsu/forza#3]
Add heartbeat plugin on a `15 || 30` second interval. We have uptime already but we should have a separate heartbeat plugin.

**Comment by mmalecki** [comment]
Why add a separate heartbeat when we can send uptime 15 || 30?

**Comment by jcrugzz** [comment]
Much easier to aggregate the data as the `metric` value for uptime is the time its been up and the service is `health/process/uptime`. Where the heartbeat service would be something like `health/process/heartbeat` and the metric would be 1. Things are always split by `host` and/or `service` so this makes things much simpler.

**Comment by mmalecki** [comment]
Word. +1.

**Comment by jcrugzz** [comment]
fixed in 096fb8bc296619e7f08adbca8a02ed0ca63a0cdf
